name: transformers-test
version: 0
description: 
  Test package for the transformers library.
  Since test frameworks and tools also depend on transformers,
  the test needs to be a separate package from the library
  in order to avoid cyclic dependencies.
  This is a long-standing known issue in Cabal: https://github.com/haskell/cabal/issues/1575

  Other packages with workarounds: 
  - ByteString
  - Containers
  - Persistent

build-type: Simple

cabal-version: 1.18
tested-with:
  ghc ==8.10
  ghc ==9.10
  ghc ==9.12
  ghc ==9.14
  ghc ==9.2
  ghc ==9.8
  mhs ==0.16

library 
  -- Empty placeholder library.
  -- Cannot have a package with test-suite only.

test-suite tests
  type: exitcode-stdio-1.0
  hs-source-dirs: .
  main-is: main.hs
  default-language: Haskell2010
  other-modules:
    Arbitrary
    ComposeT
    WriterStrictness
  build-depends:
    base                >= 4.14 && <5,

    -- Data.Solo is not available in older GHC versions
    OneTuple            >= 0.4.3 && < 0.5,

    -- tasty, QuickCheck, and ChasingBottoms depend on transformers.
    -- These are built with the published version of transformers.
    QuickCheck          >= 2.17 && < 3,
    ChasingBottoms      >= 1.3.1.17 && < 2,
    tasty               >= 1.5.4 && < 2,
    tasty-quickcheck    >= 0.11 && < 1,

    -- These are local packages.
    transformers,  
    transformers-test
